### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by alvarogzp** [alvarogzp/EventLog#2]
- [x] clean up code
- [x] differentiate test from real broadcasts in db
- [x] add test button
- [x] change app name
- [x] icon for app and for notification
- [x] improve ui
- [x] remove todos
- [x] link to https://icons8.com/license
- [x] create v9 branch with recycler view
- [ ] change to ListView to avoid api errors on v7&8 (remove support design library dependency after doing it)
- [ ] try to lower min api to 4
- [ ] try to test on v7
- [ ] make each module have a different starting package to better differentiate the module dependencies of a class -- but moves between modules won't be so clean and easy :thinking:
